ktor:
  deployment:
    port: ${SERVER_PORT:8080}
  application:
    modules:
      - dev.jskrzypczak.photovault.server.ApplicationKt.module

photovault:
  version: "1.0.0"

db:
  url: ${DB_URL:jdbc:postgresql://localhost:5432/photovault}
  user: ${DB_USER:photovault}
  password: ${DB_PASSWORD:change-me}
